### ISSUE TITLE
Write getMe GET method on UserController

### ISSUE THREAD

**Issue by Famezzs** [knurff/intellistart-java-2022-NPE_HUNTERS#12]
Requirements:

Request:
GET /me

Response:
```
{
    "email": "your@email.com",
    "role": "INTERVIEWER",
    "id": "some-UUID-only-for-COORDINATOR-or-INTERVIEWER"
}
```
#### Errors:
For Guest (unauthorized user)
```
HTTP 403
{
    "errorCode": "not_authorized",
    "errorMessage": "You are not authorized to use this functionality"
}
```

**Comment by ram333n** [comment]
11.10.2022
What I did yesterday?: Unfortunately, nothing.
What I plan to do?: I plan to watch Spring Boot tutorial and implement #13 and #14 issues.
What prevents me from doing what I need?: r*ssians and some tasks from university.

**Comment by DevPJ9** [comment]
Hello, @Famezzs I would like to contribute.
