### ISSUE TITLE
Write getCurrentWeek method on UserController

### ISSUE THREAD

**Issue by Famezzs** [knurff/intellistart-java-2022-NPE_HUNTERS#13]
Request:
GET /weeks/current

Response type:
```
{
  "weekNum": 11
}
```

**Comment by ram333n** [comment]
11.10.2022
What I did yesterday?: Unfortunately, nothing.
What I plan to do?: I plan to watch Spring Boot tutorial and implement #13 and #14 issues.
What prevents me from doing what I need?: r*ssians and some tasks from university.

**Comment by ram333n** [comment]
13.10.2022
What I did yesterday?
I watched short SpringBoot tutorial, implemented core functionality and wrote tests for this and #14 issues.

What I plan to do?
I plan to implement output in JSON format in this and #14 issues, start to implement #12 issue.

What prevents me from doing what I need?
Some problems with electricity
