### ISSUE TITLE
Write getNextWeek method on UserController

### ISSUE THREAD

**Issue by Famezzs** [knurff/intellistart-java-2022-NPE_HUNTERS#14]
Request:
GET /weeks/next

Response type:
```
{
  "weekNum": 12
}
```

**Comment by ram333n** [comment]
11.10.2022
What I did yesterday?: Unfortunately, nothing.
What I plan to do?: I plan to watch Spring Boot tutorial and implement #13 and #14 issues.
What prevents me from doing what I need?: r*ssians and some tasks from university.

**Comment by ram333n** [comment]
Task implemented in #13 issue
