### ISSUE TITLE
Create Postman collection for completed endpoints

### ISSUE THREAD

**Issue by knurff** [knurff/intellistart-java-2022-NPE_HUNTERS#35]
At the moment completed and need to add in collection:
1. Get all interviewers
2. Get all coordinators
3. Get current week
4. Get next week

**Comment by DevPJ9** [comment]
Hello, @knurff I would like to contribute.

**Comment by knurff** [comment]
> Hello, @knurff I would like to contribute.

Hello, thank you for your interest in our project, but unfortunately I can't give you the right to counterbid, as the composition of our team is strictly regulated according to the task.
