### ISSUE TITLE
Write createSlot method on CandidateController

### ISSUE THREAD

**Issue by Famezzs** [knurff/intellistart-java-2022-NPE_HUNTERS#7]
Requirements:
      The slot should be in the future
      The interval must be 1.5 hours or more and rounded to the nearest 30 minutes
      A slot is defined as an exact date and time range

Request:
POST /candidates/current/slots

**Comment by andriimanzar** [comment]
> Requirements: The slot should be in the future The interval must be 1.5 hours or more and rounded to the nearest 30 minutes A slot is defined as an exact date and time range
> 
> Request: POST /candidates/current/slots

Yesterday, I implemented candidate time slot validation in createSlot method. Today, I'm planning to implement unit tests for this method
